#!/usr/bin/env bash
# Regenerate SCORECARD.md from golden_report + manifest metadata.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/SCORECARD.md"
REPORT="$(
  cd "$ROOT/crates/steprs-core"
  cargo run -q --example golden_report --no-default-features 2>&1
)"

cat >"$OUT" <<EOF
# steprs.dev Golden Scorecard

Auto-generated by \`scripts/generate-scorecard.sh\`. Do not edit by hand.

Product scope: CAM triage (header, holes, stock, topology export). Geometry heuristics — not PMI certification.

## Gate summary

| Gate | Enforced by | What |
|------|-------------|------|
| 1 | \`golden_report\` | Per-hole identity precision/recall (strict tier) |
| 2 | \`golden_suite\` | Hole counts, kinds, units, bbox, AAG bounds |
| 3 | \`golden_suite\` | Parse time budgets |
| 4 | \`golden_suite\` | \`known_limitations\` documented |

## Latest run

\`\`\`
$REPORT
\`\`\`

## Known limitations

See \`crates/steprs-core/tests/fixtures/golden/manifest.json\` → \`known_limitations\`.

## Regenerate

\`\`\`bash
./scripts/generate-scorecard.sh
\`\`\`
EOF

echo "Wrote $OUT"
